### PR TITLE
fix(java): work around remote validation error on Android 6

### LINKED ISSUE #87: [Android] License validation issue MIUI Android 6 / others Android 4.x
Hey There.
We've recently added your module to our project with licenses for debug and release versions.
Nothing past adding the module and license info.
After checking through logcat i came across this.

```
06-12 23:42:08.464 2893-2893/com.stumble.debug D/NOTIFEE: (License): Remote verification started.
06-12 23:42:08.464 2893-2893/com.stumble.debug D/License: License key found from resources: *license for debug app here*
06-12 23:42:08.474 2893-2893/com.stumble.debug E/License: java.security.spec.InvalidKeySpecException: java.lang.RuntimeException: error:0D0680A8:asn1 encoding routines:ASN1_CHECK_TLEN:wrong tag
        at com.android.org.conscrypt.OpenSSLKey.getPrivateKey(OpenSSLKey.java:180)
        at com.android.org.conscrypt.OpenSSLRSAKeyFactory.engineGeneratePrivate(OpenSSLRSAKeyFactory.java:64)
        at java.security.KeyFactory.generatePrivate(KeyFactory.java:187)
        at n.o.t.i.f.e.e.nZ_i.nz_n(SourceFile:132)
        at app.notifee.core.Worker.nz_n(SourceFile:27)
        at app.notifee.core.Worker.lambda$6bc3g2OwlMH0Cmb2IhUkkKcXUN0(SourceFile)
        at app.notifee.core.-$$Lambda$Worker$6bc3g2OwlMH0Cmb2IhUkkKcXUN0.attachCompleter(lambda)
        at androidx.concurrent.futures.CallbackToFutureAdapter.getFuture(CallbackToFutureAdapter.java:102)
        at app.notifee.core.Worker.startWork(SourceFile:1)
        at androidx.work.impl.WorkerWrapper$1.run(WorkerWrapper.java:281)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5221)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
     Caused by: java.lang.RuntimeException: error:0D0680A8:asn1 encoding routines:ASN1_CHECK_TLEN:wrong tag
        at com.android.org.conscrypt.NativeCrypto.d2i_PKCS8_PRIV_KEY_INFO(Native Method)
        at com.android.org.conscrypt.OpenSSLKey.getPrivateKey(OpenSSLKey.java:178)
        at com.android.org.conscrypt.OpenSSLRSAKeyFactory.engineGeneratePrivate(OpenSSLRSAKeyFactory.java:64) 
        at java.security.KeyFactory.generatePrivate(KeyFactory.java:187) 
        at n.o.t.i.f.e.e.nZ_i.nz_n(SourceFile:132) 
        at app.notifee.core.Worker.nz_n(SourceFile:27) 
        at app.notifee.core.Worker.lambda$6bc3g2OwlMH0Cmb2IhUkkKcXUN0(SourceFile) 
        at app.notifee.core.-$$Lambda$Worker$6bc3g2OwlMH0Cmb2IhUkkKcXUN0.attachCompleter(lambda) 
        at androidx.concurrent.futures.CallbackToFutureAdapter.getFuture(CallbackToFutureAdapter.java:102) 
        at app.notifee.core.Worker.startWork(SourceFile:1) 
        at androidx.work.impl.WorkerWrapper$1.run(WorkerWrapper.java:281) 
        at android.os.Handler.handleCallback(Handler.java:739) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.app.ActivityThread.main(ActivityThread.java:5221) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694) 
06-12 23:42:09.725 2893-2952/com.stumble.debug D/NOTIFEE: (License): Remote verification API responded.
06-12 23:42:09.732 2893-2952/com.stumble.debug D/NOTIFEE: (License): Remote verification completed with status: 2
```

Also our config json file is laid out as follows.

```
{
	"android": {
		"release": {
			"license": "key here but removed"
		},
		"debug": {
			"license": "key here but removed"
		}
	},
	"ios": {
		"release": {
			"license": "key here but removed"
		},
		"debug": {
			"license": "key here but removed"
		}
	}
  }
```

### PR DESCRIPTION
**Pull request by mikehardy**
Fixes #87

Includes core PR https://github.com/invertase/notifee/pull/53

### CODE REVIEW

**Comment by mikehardy** [comment]
I deleted this branch then remembered I had published it for test integration for users, then restored it - I will wait for a formal release to delete it :-)

**Comment by helenaford** [comment]
OK. that makes sense. There's some conflicts on the other branch. In hindsight, shouldn't have merged.

**Comment by mikehardy** [comment]
easy to rebase push that one - I'll sort that in just a second. What I think is an interesting technical note and is the reason for those conflicts is that the framework compilation - when the 3 flavor-specific frameworks (ios, simulator, catalyst) are stitched together into the big framework it is non-deterministic. They switch around their order amongst themselves in the files even though the stanzas are the same. Makes no sense to me and I feel like I should file an upstream bug for them to do an alpha sort or something

Anyway, that's the reason for it, I'll re-push the other branch in a sec

**Comment by mikehardy** [comment]
Ah you beat me to it :-). Looks like it was also the framework delete, anyway it's all automated build so no troubule :)

**Pull request merged**
