### PR TITLE
feat(android): add gradle task to support multiple configs

### PR DESCRIPTION
**Pull request by helenaford**

### CODE REVIEW

**Comment by davidgovea** [comment]
This is great! :+1: 

Will this allow for changing the config per-flavor as well, or just by build type (e.g. `debug`, `release`)?

I'm not too familiar with gradle tasks, but it looks to me like only build type is currently considered, via `notifee.config.<builldType>.json` (e.g. `notifee.config.debug.json`)

---

I have enjoyed how google/firebase handles this with their `google-services.json` file: https://developers.google.com/android/guides/google-services-plugin#adding_the_json_file.

If this approach were taken, the notifee config could sit at paths like:
```sh
src/<buildType>/notifee.config.json
src/<flavor>/notifee.config.json
# or even
src/<buildType>/<flavor>/notifee.config.json
```
and the android build system would be fully leveraged.

**Comment by Salakar** [comment]
@davidgovea we'll look at adding flavor support in another PR

**Comment by mikehardy** [comment]
Hey guys, just to note this is a blocker for me. I'm integrating right now and I've got 1 primary for each of ios + android and 3 secondaries for each of the 2 platforms

Here's the thing though - it doesn't need to be this hard right? With gradle stuff etc etc for license validation
The notifee.config.json could have it's validator tuned so that if there was not a 'license' element, but there *was* an element that matched the bundle/package, with a license in it, it used that one.

Then I could keep all my licenses in one config file which is actually ideal. I only want one config if at all possible

This seems like some easy coding in the existing well-tested pathways vs some fresh code in the infrastructure (gradle / xcode) bits.

Thoughts?

**Comment by Salakar** [comment]
@davidgovea I've just pushed some stuff to support any flavor or build type, It's no longer file name based as to be honest I think this could get spammy with the number of files (especially as its cross platform). 

It now works based on nesting keys (keys being either the build type or flavor name) in the json file; for example, if I had a flavor called `full` I can do all sorts of scenarios of conditional config in the json file:

```json
{
  "android": {
    "release": {
      "license": "release.license"
    },
    "debug": {
      "license": "debug.license"
    },
    "full": {
      "debug": {
        "license": "full.debug.license"
      },
      "license": "full.license"
    },
    "license": "license"
  },
  "ios": {}
}
```

Config also supports falling back to the next level up config, e.g. a `full` `release` build would fall back to `android.full.license`.

**Comment by tad3j** [comment]
@Salakar , was just wondering...I guess using `.js` file instead of `.json` is not an option? ...this way way could easily get env vars in there. Would there be an alternative for defining licenses through them?

**Comment by nekhaly** [comment]
Would we have the same feature for iOS different executables?

**Comment by mikehardy** [comment]
@nekhaly I believe that is the goal yes, and in current practice I think you will find in testing that it works, in that you are able to post local notifications on iOS in release builds with a similar config for iOS? It works in my testing

**Comment by igor-bv** [comment]
In case if for android config the key could a flavor name, then what is the value must be for ios key(target name probably)?
I'm using different env configs and each env has debug and release build configuration.

**Comment by mikehardy** [comment]
@igor-bv that's a good question, I believe it should be roughly the same but on iOS the concept of flavor is mapped to scheme

Have you tried it? If there are no errors in Xcode console and notifications work, it's hooked up I believe

```
{
  "android": {
    "dev": {
      "license": "..."
    },
    "qa": {
      "license": "..."
    },
    "staging": {
      "license": "..."
    },
    "prod": {
      "license": "..."
    }
  },
  "ios": {
    "Dev": {
      "license": "..."
    },
    "Test": {
      "license": "..."
    },
    "Staging": {
      "license": "..."
    },
    "Prod": {
      "license": "..."
    }
  }
}
```

**Comment by igor-bv** [comment]
@mikehardy , thanks for response!
I tried to set scheme names as keys in notifee.config.json, but in `Rlease` build confguration local notifications are not work, in `Debug` - everything is ok.

My config looks like:
```
{
  "ios": {
     "app-staging": {
       "license": "..."
     },
     "app-production": {
       "license": "..."
     }
  }
}
```

Where `app-staging` and `app-production` are ios schemes names.

**Comment by mikehardy** [comment]
I think there must be something else going on. If it is license verification failing you'll see obvious reports in the xcode log on the device when running the app

I suspect there is something else you'll see in the logs

**Comment by lorenc-tomasz** [comment]
Hi all,
I guess those information should be added into documentation how to exactly use this. @helenaford @Salakar what do you think?

**Comment by mikehardy** [comment]
It definitely should! I was moving too quickly and should have noted that in the related issue, I left it open as it still had a doc update as a pending item

**Comment by cjpete** [comment]
Is there a good way of validating that the right license has been bundled with the right app? 

It would be useful to have a debug mode or something that prints out the license key (or some kind of identifiable substring of it) that it has found for the current build.

I'm using the following configuration, in the hope that if all else fails it will default back to the production license - as those are the notifications that we definitely want to go through:

```
{
  "android": {
    "development": {
      "license": "[dev android license]"
    },
    "staging": {
      "license": "[staging android license]"
    },
    "license": "[production android license]"
  },
  "ios": {
    "development": {
      "license": "[dev ios license]",
    },
    "staging": {
      "license": "[staging ios license]",
    },
    "license": "[production ios license]"
  }
}
```

Where on iOS my scheme names are `staging`, `production`, `storybook`, and `development`, and on Android my productFlavors are named the same respectively.

**Comment by mikehardy** [comment]
There is not a good way to validate it at the moment. That would be useful, I'm +1 on the idea personally

```json
{
  "android": {
    "dev": {
      "license": "..."
    },
    "qa": {
      "license": "..."
    },
    "staging": {
      "license": "..."
    },
    "prod": {
      "license": "..."
    }
  },
  "ios": {
    "dev": {
      "license": "..."
    },
    "test": {
      "license": "..."
    },
    "staging": {
      "license": "..."
    },
    "release": {
      "license": "..."
    }
  }
}
```

You can see I use "release" as the fallback in ios, I do not actually have a fallback on android but my 4 flavors all note they are validating correctly so without fallback I must assume they are configured correctly (in the absence of the API idea for positive license confirmation). I'm not sure if your fallback config is actually doing what you want then as I name all flavors.

Hope this helps, in a comparing notes way

**Pull request merged**
