### PR TITLE
chore(android): bump Gradle wrapper version to 6.0.1

### PR DESCRIPTION
**Pull request by SaeedZhiany**

### CODE REVIEW

**Comment by mikehardy** [comment]
this is not a warning, just a notice that apparently there are gradle bundling issues between hermes and the JSC with gradle 6. I am using it successfully in my project but I don't use hermes. Just keep an eye out of someone reports it blowing up

**Comment by Salakar** [comment]
We're using Hermes on our internal mono-repo - so should flag up pretty quickly if theres an issue

**Comment by mikehardy** [comment]
It's the sort of thing where things that should not be packed are, if you try apk explorer you might see it? discussed on discord android or hermes I believe, and probably a github issue but I'm not tracking super close

**Comment by Salakar** [comment]
Just seen the discussion on discord (android channel) - it appears to only be an issue when building an app with RN thats on Gradle 6 - this change here is fine as it's only the wrapper for the library - have tested locally and all is ok 🤞

**Comment by SaeedZhiany** [comment]
Yeah, I read it before but I couldn't find the discussion to share with you two.

**Pull request merged**
