### PR TITLE
feat(iOS): trigger notifications

### PR DESCRIPTION
**Pull request by helenaford**

### CODE REVIEW

**Comment by davidgovea** [comment]
neato!

**Comment by helenaford** [comment]
@davidgovea thanks 😄

**Comment by nicocolascrete** [comment]
Have you an idea when createTriggerNotification will be available?

Thanks :)

**Comment by mahpat16** [comment]
@helenaford  Any update on this? Is trigger notifications available on IoS. The documentation of createTriggerNotification says Android Only, even the examples are for android. On the other hand I saw an issue related to cancelTriggerNotifications that mentions that cancel is available on ios as well. So is create available too?

**Comment by mikehardy** [comment]
@mahpat16 the docs may need an update but this branch was merged and released, it should be working on iOS? Have you tried it?

**Comment by helenaford** [comment]
@mahpat16 yes it's been released. I can see the Android label for `createTriggerNotification` on the reference docs,  will remove it. thanks for letting us know 👍  The examples can work for both platforms.

**Pull request merged**
