### PR TITLE
feat(android): media style notification

### PR DESCRIPTION
**Pull request by helenaford**
On-going work to allow Media Style Notifications to be created with Notifee (more in-depth discussion on #9).

If you'd like to try out the new feature, please follow the below steps:
1.   Adjust your package.json to include
` "@notifee/react-native": "notifee/react-native-notifee.git#@helenaford/android-media-style-notifications",`
2. add a postinstall step to package.json
   ` "postinstall": "cd node_modules/@notifee/react-native && yarn"`
3. Install react-native-track-player, if you do not have it already
`"react-native-track-player": "^1.2.3"`
4. Create the notification:
```
    const notification =  {
      id: 'media-track',
      title: 'Song Title',
      body: 'Artist Name',
      android: {
        style: {
          type: AndroidStyle.MEDIA,
        },
        largeIcon: 'url/to/album/artwork',
        actions: [
          {
            title: 'Play',
            pressAction: {
              id: 'play',
            },
          },
        ],
        channelId: 'channel',
      },
    };
```
5. display vis `Notifee.displayNotification(notification)` or trigger the notification via `createTriggerNotification(notification, [your-trigger])`
6. Listen for incoming event to start playing the audio via RNTP (React Native Track Player)

```
Notifee.onForegroundEvent(async event => {
   // To automatically play once notification is received
    if (event.type === EventType.DELIVERED) {
      await TrackPlayer.add({
        id: 'media-track',
        url: 'url/to/track',
        title: 'Song Title',
        artist: 'Artist Name',
        artwork: 'url/to/artwork',
        duration: 28,
      });
  
      await TrackPlayer.play();
     }
      
      // To play once action is press
      if (event.type === EventType.ACTION_PRESS && event.detail?.pressAction?.id === 'play') {
          cancelNotification('media-track');
         // play track
      }
  }
```

### CODE REVIEW

**Comment by VivienTournie** [comment]
@helenaford Aren't we supposed to have acces to this ?
image
My package.json :
```
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint .",
    "postinstall": "cd node_modules/@notifee/react-native && yarn"
  },
```

**Comment by helenaford** [comment]
Oh the url is wrong, think it's the difference between using yarn and npm.

**Comment by VivienTournie** [comment]
Sadly I couldn't find a way to use this with npm after many tries.

Seems like there is some known issues with dependencies using npm. I'll have to wait for the next Notifee version, hoping this p/r will be included.

**Comment by VivienTournie** [comment]
Sadly I couldn't find a way to use this with npm after many tries.

Seems like there is some known issues with dependencies using npm. I'll have to wait for the next Notifee version, hoping this p/r will be included. Do you have an ETA by any chance ?

**Comment by mikehardy** [comment]
While I fully understand that dependency manager choice is both project-specific and perhaps difficult to change this is one of the reasons I switched to yarn. The main reason though: have you ever done a speed comparison between the two? Oh my, yarn is faster! Worth a thought. You could likely just rm package-lock.json temporarily in a local branch and use yarn to temporarily integrate this for testing, for what it's worth - I think we need the customer validation that it works prior to including it so it might be a catch-22 / chicken-vs-egg problem otherwise

**Comment by VivienTournie** [comment]
I'm willing to swap to yarn, but I'm not using typescript in my project and it seems that it creates problems.
So I just followed the steps mentionned here : https://stackoverflow.com/a/51255470/5045416 then here https://classic.yarnpkg.com/en/docs/migrating-from-npm/

And as expected, nothing is simple with React Native😄
image

I'll try to figure out what's the problem, but from what I understand, it seems related to typescript : 

image

As a experienced yarn user @mikehardy  , can you confirm my guess ? Am I forced to use/install typescript to use yarn ?

**Comment by mikehardy** [comment]
typescript is not the problem :-), you are likely close. The problem is that *we* use typescript, and now that you are depending on a git reference you are receiving a source code (i.e., typescript) distribution/install while node of course needs to consume javascript. The missing step is that you need to compile the typescript to javascript *then* it will work.

Here is what I have in my postinstall in package.json when I am depending on `@notifee/react-native` as a git reference instead of a published version:

`cd node_modules/@notifee/react-native && yarn`

But! I have typescript in my project already, you may need to 'yarn add typescript' temporarily so that `tsc` ("typescript compiler") can run and generate things

I appreciate your working through this stuff and giving it a shot, I think you're nearly there - just need to make it so that typescript is available and does the notifee typescript-source-to-javascript build and you should be in business

**Comment by VivienTournie** [comment]
Thanks for the help mikehardy :)

@helenaford , I gave it a try, and I have strange behavior with the player. I don't understand how do you listen the sound "inside" the notifee media style notification. In my case, the RNTP player also appears.
Example :
image

Could you please show the code you used to have the same behavior as https://github.com/notifee/react-native-notifee/issues/9#issuecomment-760408134 ?

I'll try tomorrow to make it work with onBackgroundEvent (my real use case, because my app is an alarm clock 😄)

**Comment by helenaford** [comment]
thanks for trying it out @VivienTournie. so there's multiple things here around this... 

1. There needs to be a change to the react-native-track-player library where their notification uses the same id as ours (which is what I did locally)... so they can be automatically updated. 
2. Without the change, you'd have to cancelNotificaiton, and then play() which i'll update in my example code at the top. I'm wondering if I can do this with a patch, but I need to look into it because it's native code that's changing.

**Comment by helenaford** [comment]
@VivienTournie are you on discord, we could chat over on the invertase discord channel (https://invertase.link/discord)? I'm interested to know if this p/r helped you at all with your use case?

**Comment by VivienTournie** [comment]
@helenaford Yes I am. I'll message you on discord asap !

**Comment by VivienTournie** [comment]
@helenaford Have you ever posted a message on the invertase discord channel ? I can't find a single message from you 😆 (or maybe I'm looking for the wrong name 🙄 )

**Pull request closed without merging**
